### ISSUE TITLE
Wallets with many tokens fail to load

### ISSUE THREAD

**Issue by refi93** [vacuumlabs/adalite#1100]
Wallets with many tokens seem to experience ServerError when loading, probably related to the related token registry request being too big

Potentially related server logs:

```
140 <190>1 2021-08-24T05:00:28.409338+00:00 app web.1 - - PayloadTooLargeError: request entity too large
    at readStream (/app/node_modules/raw-body/index.js:155:17)
    at getRawBody (/app/node_modules/raw-body/index.js:108:12)
    at read (/app/node_modules/body-parser/lib/read.js:77:3)
    at jsonParser (/app/node_modules/body-parser/lib/types/json.js:135:5)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
    at /app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
    at next (/app/node_modules/express/lib/router/index.js:275:10)
    at Domain.<anonymous> (/app/node_modules/@sentry/node/dist/handlers.js:247:13)
```

**Comment by refi93** [comment]
addressed by non-blocking loading of token metadata introduced in https://github.com/vacuumlabs/adalite/releases/tag/v6.7.0
