### ISSUE TITLE
TransactionCorruped error observed intermittently

### ISSUE THREAD

**Issue by refi93** [vacuumlabs/adalite#645]
Transaction serialization seems to be failing under certain (yet unknown) circumstances. Error stack:

```
TransactionCorrupted: {"message":"","name":"TransactionCorrupted","stack":"TransactionCorrupted\n    at Object.NamedError [as default] (https://adalite.io/js/frontend.bundle.js:3996:15)\n    at confirmTransaction (https://adalite.io/js/frontend.bundle.js:2927:39)\n    at ...
  at Object.NamedError [as default](webpack://CardanoFrontend/./frontend/helpers/NamedError.ts:2:13)
  at confirmTransaction(webpack://CardanoFrontend/./frontend/actions.ts:362:23)
  at ? (webpack://CardanoFrontend/./frontend/libs/unistore/index.js:60:1)
  at SendAdaPage.<anonymous>(webpack://CardanoFrontend/./frontend/components/pages/sendAda/sendAdaPage.tsx:104:13)
  at Generator.next(<anonymous>)
  at ? (webpack://CardanoFrontend/./frontend/components/common/conversions.tsx:24:27)
  at new Promise(<anonymous>)
  at __awaiter(webpack://CardanoFrontend/./frontend/components/common/conversions.tsx:24:27)
  at Object.submitHandler [as click](webpack://CardanoFrontend/./frontend/components/pages/sendAda/sendAdaPage.tsx:103:38)
  at HTMLButtonElement.N(webpack://CardanoFrontend/./node_modules/preact/dist/preact.module.js:1:3910)
```

look into Sentry for `TransactionCorruped` error for more context

**Comment by PeterBenc** [comment]
I was thinking about adding a context to the errors we send to Sentry, see [sentry_docs](https://docs.sentry.io/platforms/javascript/#passing-context-directly). We could send the whole prepared tx plan to sentry and see what went wrong. Of course, better would be to fix this bug without it happening to another user.

**Comment by refi93** [comment]
that would be great, though we should also not discard the original error stack when rethrowing them as named errors - IMHO that would already provide us with enough information to figure out this and potentially other problems (that are not necessarily related to transaction assembly/signing)

**Comment by xdzurman** [comment]
Passing [error stack](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/stack) to NamedError function should solve this.

**Comment by PeterBenc** [comment]
With the error stack, we discovered that the txPlan si null in the moment its used. We already pushed a fix for this so closing.
