### ISSUE TITLE
Locally failing Wallet export test

### ISSUE THREAD

**Issue by PeterBenc** [vacuumlabs/adalite#907]
When running tests locally, this happens
```
Wallet export
(node:12463) UnhandledPromiseRejectionWarning: Error: Page crashed!
    at Page._onTargetCrashed (/home/peter/Vacuum/adalite/app/node_modules/puppeteer/lib/Page.js:170:24)
    at CDPSession.Page.client.on.event (/home/peter/Vacuum/adalite/app/node_modules/puppeteer/lib/Page.js:125:56)
    at CDPSession.emit (events.js:197:13)
    at CDPSession._onMessage (/home/peter/Vacuum/adalite/app/node_modules/puppeteer/lib/Connection.js:200:12)
    at Connection._onMessage (/home/peter/Vacuum/adalite/app/node_modules/puppeteer/lib/Connection.js:112:17)
    at WebSocketTransport._ws.addEventListener.event (/home/peter/Vacuum/adalite/app/node_modules/puppeteer/lib/WebSocketTransport.js:44:24)
    at WebSocket.onMessage (/home/peter/Vacuum/adalite/app/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:197:13)
    at Receiver.receiverOnMessage (/home/peter/Vacuum/adalite/app/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (events.js:197:13)
(node:12463) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12463) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by refi93** [comment]
fixed in #1361
